name: Check for removed files

on: 
  push:
    paths:
       - "content/"
  workflow_dispatch:
  
jobs:
  check-removed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          # Use the `git diff` command to check for removed files
          git diff --name-only HEAD~2 HEAD~1

          # If the output of the above command is not empty, it means that one or more files were removed
          # Use the `set-output` action to set the output variable "removed_files"
          if: [ -n "$output" ]
            echo "One or more files were removed"
            set-output name=removed_files value=true
          if: ! [ -n "$output" ]
            echo "No files were removed"
            set-output name=removed_files value=false
