name: Check for removed files

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "contents/"

jobs:
  check-removed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: removed-files
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          # Use the `git diff` command to check for removed files
          git diff --name-only HEAD~2 HEAD~1

          for file in ${{ steps.removed-files.outputs }}; do
            echo $file >> files.txt
          done
          

