name: Check for removed files

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "contents/**"

jobs:
  check-removed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: removed-files
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          # Use the `git diff` command to check for removed files
          git diff --name-only HEAD~1 HEAD~0 --diff-filter=D

          # touch files.txt
          for file in ${{ steps.removed-files.outputs }}; do
            echo $file >> files.txt
          done
      - uses: "finnp/create-file-action@master"
        env:
              FILE_NAME: "dir/filename.txt"
              FILE_DATA: steps.removed-files.outputs
       
          

