name: Prevent removal of member
on:
  push:
    branches: [ "main" ]
    paths:
      - "content/"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-members
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Function 1
      - name: Compare members
        run: python ./check_members_removal.py

