name: Prevent removal of member
on:
  push:
    branches: [ "main" ]
    paths:
      - "content/"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-members
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
          
      # Function 1
      - name: get changed members
        id: changed-members
        uses: tj-actions/changed-files@v34
        with:
          commit_message: Update members
          file_pattern: contents/*
        
      - name: List all removed members
        run: |
          for member in ${{ steps.changed-members.outputs.deleted_files }}; do
            echo "$member was removed"
          done

