name: Member removal notification
on:
  push:
    branches: 
      - main
    paths:
      - 'contents/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:        
      - name: Notify dedicated teams channel
        if: ${{ github.event.head_commit.removed != '' }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.TEAMS_CHANNEL_WEBHOOK_URL }}
          notification-summary: 'Warning! A member file has been removed. Contact someone from the Webteam and make sure the member is added back.'
          notification-color: 17a2b8
