on:
  push:
    paths:
      - '!*.md' # Change this to the file extension or name you want to track

jobs:
  notify-on-file-removal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify on file removal
        uses: microsoft/teams-notify@v1
        with:
          webhook: ${{ secrets.TEAMS_CHANNEL_WEBHOOK_URL }}
          title: File removed
          message: A file has been removed in a commit.
          summary: "The following file has been removed: ${{ github.event.head_commit.removed | join(', ') }}"
          themeColor: '0072C6'
          activityImage: 'https://github.com/github.png'
          activityTitle: 'GitHub'
          activitySubtitle: '${{ github.event.repository.name }}'
          activityText: 'File removal notification'
        if: ${{ github.event.head_commit.removed && github.event.head_commit.removed | length > 0 }}
    
